name: Build APK

on: 
  workflow_dispatch:

jobs:
  build_apk:
    runs-on: ubuntu-latest
    env: # ADD environment variables
      PROPERTIES_PATH: "./android/key.properties"
      ALIAS_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
      JAVA_VERSION: "11.x"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: ${{env.JAVA_VERSION}}
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.5'
          channel: 'stable'
          cache: true
          architecture: x64 
      - name: Create key file
        run: |
          echo keyPassword=\${{ secrets.KEY_PASSWORD }} > ${{env.PROPERTIES_PATH}}
          echo storePassword=\${{ secrets.KEY_PASSWORD }} >> ${{env.PROPERTIES_PATH}}
          echo keyAlias=\${{ secrets.ALIAS_PASSWORD }} >> ${{env.PROPERTIES_PATH}}
          echo "${{ secrets.KEY_JKS }}" | base64 --decode > android/app/key/KHKeyStore.jks
      - run: flutter pub get
      - run: flutter build appbundle --release
      - uses: actions/upload-artifact@v3
        with:
          name: release-dev-apk
          path: build/app/outputs/bundle/release/app-release.aab