name: Build APK

on: 
  workflow_dispatch:

jobs:
  build_apk:
    runs-on: macos-latest
    env: # ADD environment variables
      KEY_JKS: ${{ secrets.KEY_JKS }}
      KEY_PATH: ${{ github.workspace }}/key.jks
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      ALIAS_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.5'
          channel: 'stable'
          cache: true
          architecture: x64 
      - name: Create key file
        run: echo $KEY_JKS | base64 -di > key.jks 
      - run: flutter pub get
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v3
        with:
          name: release-dev-apk
          path: build/app/outputs/apk/release/app-release.apk